[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
segmented_button = { path = "../" }
iced = { version = "0.10", features = ["image", "svg", "smol"] }
iced_widget = "0.1.3"
