[package]
name = "segmented_button"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced_core = "0.10.0"
iced_style = "0.9.0"
iced_widget = { version = "0.1.3", features = ["svg"] }
